services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_storage:/root/.ollama
    restart: always

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama-pull
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=ollama:11434
    command: pull qwen2.5-coder:0.5b

  litellm:
    image: ghcr.io/berriai/litellm:lastest
    container_name: litellm
    ports:
      - "4000:4000"
    volumes:
      # KITA UBAH DISINI: Me-mount folder 'litellm' ke dalam '/app/config_folder'
      - ./litellm:/app/config_folder
    # Memerintahkan LiteLLM membaca file di dalam folder tersebut
    command: [ "--config", "/app/config_folder/litellm_config.yaml", "--port", "4000", "--host", "0.0.0.0" ]
    depends_on:
      - ollama
    restart: always

volumes:
  ollama_storage: